### ISSUE TITLE
upstream generic fixes to flyspray project

### ISSUE THREAD

**Issue by peterdd** [mol-pl/flyspray#1]
Hello ecconux,

I would be glad to have some more people contribute to Flyspray and for getting Flyspray1.0 release ready.

As I see you use Flyspray with PostgreSQL, I would be glad if you give the Flyspray github master version a shot and test the current Flyspray github master with Postgresql and typical database sample data.

I see you added jquery to mol/flyspray, but use the old theme and template 'engine'.
The javascript overhaul is planned for FS1.1  (see https://bugs.flyspray.org/1737 ), but having some people with good javascript knowledge would be great.

My aims: up to date javascript versions of the current scripts/features while keeping main features usable when js is disables; no more inline JS; use of ContentSecurityPolicy settings for enhanced security.

Greetings, peterdd

**Comment by Eccenux** [comment]
Sorry, as you might have noticed, we don't have resources for that.
